# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grpc_server_template.proto for package ''

require "grpc"
require_relative "messages"

module GrpcServerTemplate
  # The greeting service definition.
  class Service
    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = "GrpcServerTemplate"

    rpc :SayHello, GrpcServerTemplate::Messages::HelloRequest, GrpcServerTemplate::Messages::HelloReply
  end

  Stub = Service.rpc_stub_class
end
